[package]
name = "numid"
version = "0.1.0"
authors = ["Nicolas Poelen"]
edition = "2018"

description = "A macro for generating structures which behave like numerical id."
licence = "MIT"
keywords = ["macro", "id", "struct"]
readme = "README.md"
repository = "https://github.com/powlpy/numid"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
