//! This module shows an example of code generated by the `numid` macro.
//! **IT MUST NOT BE USED OUTSIDE THIS CRATE**.

numid!(#[doc = "This structure example is generated with the macro call : `numid!(#[doc=…] pub struct NumId);`."]
pub struct NumId);

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let id = super::NumId::new();
        assert!(id.value() != 0);
    }
}
